language: java
jdk:
  - oraclejdk8
  
notifications:
  webhooks: https://travis-buddy-service.herokuapp.com
  
before_install:
 - chmod +x ./build/prepareTasks.sh
 - ./build/prepareTasks.sh
 
before_script:
  - chmod +x ./build/compileTasks.sh
  
script:
  - TASKS=(Task06 Task07)
  - ./build/compileTasks.sh ${TASKS[@]}
  
